[build]
command = "npm run build"
publish = "dist"

[build.environment]
GITHUB_TOKEN = "${GITHUB_DEPLOY_TOKEN}"  # Uses env var instead of hardcoding

[context.production.environment]
NODE_ENV = "production"

